exec --no-startup-id dunst
exec --no-startup-id fcitx5 -d
exec --no-startup-id picom -b
exec_always --no-startup-id feh --bg-fill /home/avatar/Pictures/eclipse.png
exec --no-startup-id clash-verge
exec --no-startup-id flameshot
exec --no-startup-id /usr/lib/kdeconnectd
exec --no-startup-id lxpolkit
exec --no-startup-id kdeconnect
